version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - APP_SETTINGS=config.config.DevelopmentConfig
      - DATABASE_URL=postgresql+psycopg2://postgres:password@db:5432/app_db
    volumes:
      - ./backend:/app
    depends_on:
      - db
    command: >
      sh -c "
      python manage.py db upgrade &&
      python manage.py runserver"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - ./frontend:/usr/share/nginx/html
    depends_on:
      - backend

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: